In [4]:
import pandas as pd
import protfasta

In [43]:
seqs = protfasta.read_fasta("01_tair_arabidopsis_raw.fasta",
                            expect_unique_header = False,
                           duplicate_record_action = 'ignore',
                           invalid_sequence_action = 'ignore')
seqs = pd.DataFrame({"id" : seqs.keys(), "seq" : seqs.values()})
seqs

,id,seq
0,AT5G03200.1 | Symbols: LUL1 | LOG2-LIKE UBIQUI...,MGNLISLIFCCGRRQRSNIPPAMETAPLELPPNRFVFAAVPPYLNP...
1,"AT5G44110.1 | Symbols: ATNAP2, POP1, ABCI21, A...",MAEKNASAVDGAIRVSGMQFSYDVQDPIFFDFNLDLPAGSRCLLVG...
2,"AT2G27030.3 | Symbols: ACAM-2, CAM5 | calmodul...",MADQLTDDQISEFKEAFSLFDKDGDGCITTKELGTVMRSLGQNPTE...
3,AT1G23550.1 | Symbols: SRO2 | similar to RCD o...,MAAQVEIEDQTSVTNLDNGEIFDSISDDADSSVSHAGSSFSSSSLI...
4,"AT4G34240.1 | Symbols: ALDH3I1, ALDH3 | aldehy...",MTKLLEINHIQTLCFAKGFSPARLNVATSPFRISRRGGGGYCSNAC...
...,...,...
114,AT1G55320.1 | Symbols: AAE18 | acyl-activating...,MWKSIGELSCDDYVKAGLTLEDAKEFDKLVSDVITKAIETDPRDQW...
115,"AT2G01570.1 | Symbols: RGA, RGA1, RGA24 | REPR...",MKRDHHQFQGRLSNHGTSSSSSSISKDKMMMVKKEEDGGGNMDDEL...
116,"AT1G15040.1 | Symbols: GAT, GAT1_2.1 | glutami...",MVVANDLSSKILPRVLIVSRRTLRKNKYVDFVGEYHLDLIVSSGAV...
117,AT1G14980.1 | Symbols: CPN10 | chaperonin 10 |...,MMKRLIPTFNRILVQRVIQPAKTESGILLPEKSSKLNSGKVIAVGP...
118,"AT1G15020.2 | Symbols: QSOX1, QSO2, ATQSOX1 | ...",MSLIHLFLLLGLLSLEAAASFSPGSRSILRDIGSNVADQKDNAIEL...

In [44]:
seqs["gene"] = seqs["id"].str.split("Symbols: ").str[1].str.split("|").str[0].str[:-1]
seqs

,id,seq,gene
0,AT5G03200.1 | Symbols: LUL1 | LOG2-LIKE UBIQUI...,MGNLISLIFCCGRRQRSNIPPAMETAPLELPPNRFVFAAVPPYLNP...,LUL1
1,"AT5G44110.1 | Symbols: ATNAP2, POP1, ABCI21, A...",MAEKNASAVDGAIRVSGMQFSYDVQDPIFFDFNLDLPAGSRCLLVG...,"ATNAP2, POP1, ABCI21, ATPOP1"
2,"AT2G27030.3 | Symbols: ACAM-2, CAM5 | calmodul...",MADQLTDDQISEFKEAFSLFDKDGDGCITTKELGTVMRSLGQNPTE...,"ACAM-2, CAM5"
3,AT1G23550.1 | Symbols: SRO2 | similar to RCD o...,MAAQVEIEDQTSVTNLDNGEIFDSISDDADSSVSHAGSSFSSSSLI...,SRO2
4,"AT4G34240.1 | Symbols: ALDH3I1, ALDH3 | aldehy...",MTKLLEINHIQTLCFAKGFSPARLNVATSPFRISRRGGGGYCSNAC...,"ALDH3I1, ALDH3"
...,...,...,...
114,AT1G55320.1 | Symbols: AAE18 | acyl-activating...,MWKSIGELSCDDYVKAGLTLEDAKEFDKLVSDVITKAIETDPRDQW...,AAE18
115,"AT2G01570.1 | Symbols: RGA, RGA1, RGA24 | REPR...",MKRDHHQFQGRLSNHGTSSSSSSISKDKMMMVKKEEDGGGNMDDEL...,"RGA, RGA1, RGA24"
116,"AT1G15040.1 | Symbols: GAT, GAT1_2.1 | glutami...",MVVANDLSSKILPRVLIVSRRTLRKNKYVDFVGEYHLDLIVSSGAV...,"GAT, GAT1_2.1"
117,AT1G14980.1 | Symbols: CPN10 | chaperonin 10 |...,MMKRLIPTFNRILVQRVIQPAKTESGILLPEKSSKLNSGKVIAVGP...,CPN10
118,"AT1G15020.2 | Symbols: QSOX1, QSO2, ATQSOX1 | ...",MSLIHLFLLLGLLSLEAAASFSPGSRSILRDIGSNVADQKDNAIEL...,"QSOX1, QSO2, ATQSOX1"

In [45]:
seqs["tair_ID"] = seqs["id"].str.split("|").str[0].str[:-1]
seqs

,id,seq,gene,tair_ID
0,AT5G03200.1 | Symbols: LUL1 | LOG2-LIKE UBIQUI...,MGNLISLIFCCGRRQRSNIPPAMETAPLELPPNRFVFAAVPPYLNP...,LUL1,AT5G03200.1
1,"AT5G44110.1 | Symbols: ATNAP2, POP1, ABCI21, A...",MAEKNASAVDGAIRVSGMQFSYDVQDPIFFDFNLDLPAGSRCLLVG...,"ATNAP2, POP1, ABCI21, ATPOP1",AT5G44110.1
2,"AT2G27030.3 | Symbols: ACAM-2, CAM5 | calmodul...",MADQLTDDQISEFKEAFSLFDKDGDGCITTKELGTVMRSLGQNPTE...,"ACAM-2, CAM5",AT2G27030.3
3,AT1G23550.1 | Symbols: SRO2 | similar to RCD o...,MAAQVEIEDQTSVTNLDNGEIFDSISDDADSSVSHAGSSFSSSSLI...,SRO2,AT1G23550.1
4,"AT4G34240.1 | Symbols: ALDH3I1, ALDH3 | aldehy...",MTKLLEINHIQTLCFAKGFSPARLNVATSPFRISRRGGGGYCSNAC...,"ALDH3I1, ALDH3",AT4G34240.1
...,...,...,...,...
114,AT1G55320.1 | Symbols: AAE18 | acyl-activating...,MWKSIGELSCDDYVKAGLTLEDAKEFDKLVSDVITKAIETDPRDQW...,AAE18,AT1G55320.1
115,"AT2G01570.1 | Symbols: RGA, RGA1, RGA24 | REPR...",MKRDHHQFQGRLSNHGTSSSSSSISKDKMMMVKKEEDGGGNMDDEL...,"RGA, RGA1, RGA24",AT2G01570.1
116,"AT1G15040.1 | Symbols: GAT, GAT1_2.1 | glutami...",MVVANDLSSKILPRVLIVSRRTLRKNKYVDFVGEYHLDLIVSSGAV...,"GAT, GAT1_2.1",AT1G15040.1
117,AT1G14980.1 | Symbols: CPN10 | chaperonin 10 |...,MMKRLIPTFNRILVQRVIQPAKTESGILLPEKSSKLNSGKVIAVGP...,CPN10,AT1G14980.1
118,"AT1G15020.2 | Symbols: QSOX1, QSO2, ATQSOX1 | ...",MSLIHLFLLLGLLSLEAAASFSPGSRSILRDIGSNVADQKDNAIEL...,"QSOX1, QSO2, ATQSOX1",AT1G15020.2

In [46]:
seqs["seq_cleaned"] = seqs["seq"].str[:-1]
seqs

,id,seq,gene,tair_ID,seq_cleaned
0,AT5G03200.1 | Symbols: LUL1 | LOG2-LIKE UBIQUI...,MGNLISLIFCCGRRQRSNIPPAMETAPLELPPNRFVFAAVPPYLNP...,LUL1,AT5G03200.1,MGNLISLIFCCGRRQRSNIPPAMETAPLELPPNRFVFAAVPPYLNP...
1,"AT5G44110.1 | Symbols: ATNAP2, POP1, ABCI21, A...",MAEKNASAVDGAIRVSGMQFSYDVQDPIFFDFNLDLPAGSRCLLVG...,"ATNAP2, POP1, ABCI21, ATPOP1",AT5G44110.1,MAEKNASAVDGAIRVSGMQFSYDVQDPIFFDFNLDLPAGSRCLLVG...
2,"AT2G27030.3 | Symbols: ACAM-2, CAM5 | calmodul...",MADQLTDDQISEFKEAFSLFDKDGDGCITTKELGTVMRSLGQNPTE...,"ACAM-2, CAM5",AT2G27030.3,MADQLTDDQISEFKEAFSLFDKDGDGCITTKELGTVMRSLGQNPTE...
3,AT1G23550.1 | Symbols: SRO2 | similar to RCD o...,MAAQVEIEDQTSVTNLDNGEIFDSISDDADSSVSHAGSSFSSSSLI...,SRO2,AT1G23550.1,MAAQVEIEDQTSVTNLDNGEIFDSISDDADSSVSHAGSSFSSSSLI...
4,"AT4G34240.1 | Symbols: ALDH3I1, ALDH3 | aldehy...",MTKLLEINHIQTLCFAKGFSPARLNVATSPFRISRRGGGGYCSNAC...,"ALDH3I1, ALDH3",AT4G34240.1,MTKLLEINHIQTLCFAKGFSPARLNVATSPFRISRRGGGGYCSNAC...
...,...,...,...,...,...
114,AT1G55320.1 | Symbols: AAE18 | acyl-activating...,MWKSIGELSCDDYVKAGLTLEDAKEFDKLVSDVITKAIETDPRDQW...,AAE18,AT1G55320.1,MWKSIGELSCDDYVKAGLTLEDAKEFDKLVSDVITKAIETDPRDQW...
115,"AT2G01570.1 | Symbols: RGA, RGA1, RGA24 | REPR...",MKRDHHQFQGRLSNHGTSSSSSSISKDKMMMVKKEEDGGGNMDDEL...,"RGA, RGA1, RGA24",AT2G01570.1,MKRDHHQFQGRLSNHGTSSSSSSISKDKMMMVKKEEDGGGNMDDEL...
116,"AT1G15040.1 | Symbols: GAT, GAT1_2.1 | glutami...",MVVANDLSSKILPRVLIVSRRTLRKNKYVDFVGEYHLDLIVSSGAV...,"GAT, GAT1_2.1",AT1G15040.1,MVVANDLSSKILPRVLIVSRRTLRKNKYVDFVGEYHLDLIVSSGAV...
117,AT1G14980.1 | Symbols: CPN10 | chaperonin 10 |...,MMKRLIPTFNRILVQRVIQPAKTESGILLPEKSSKLNSGKVIAVGP...,CPN10,AT1G14980.1,MMKRLIPTFNRILVQRVIQPAKTESGILLPEKSSKLNSGKVIAVGP...
118,"AT1G15020.2 | Symbols: QSOX1, QSO2, ATQSOX1 | ...",MSLIHLFLLLGLLSLEAAASFSPGSRSILRDIGSNVADQKDNAIEL...,"QSOX1, QSO2, ATQSOX1",AT1G15020.2,MSLIHLFLLLGLLSLEAAASFSPGSRSILRDIGSNVADQKDNAIEL...

In [47]:
seqs[seqs["seq_cleaned"].str.contains("\*")]

Empty DataFrame
Columns: [id, seq, gene, tair_ID, seq_cleaned]
Index: []

In [49]:
protfasta.write_fasta(dict(zip(seqs["gene"], seqs["seq_cleaned"])), "01_tair_arabidopsis_cleaned.fasta")

In [51]:
seqs.to_csv("01d_tair_arabidopsis_cleaned.csv")